spring:
  main:
    web-application-type: none
  datasource:
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:${PORT}/${DATABASE_NAME}
  jpa:
    properties:
      hibernate:
        show_sql: true
        default_schema: ${SCHEMA}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
google:
  credential:
    path: classpath:tokens/google_credential.json

application:
  image-url: Img/icon.ico
  slat: ${SECRET}
  user: ${USER_WINDOW}