spring:
  main:
    web-application-type: none
  datasource:
    username: ${USER_NAME :database}
    password: ${PASSWORD :secret@passs}
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=name
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL :BloemistBot@gmail.com}
    password: ${EMAIL_PASSWORD :x}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  image-url: Img/icon.ico