spring:
  main:
    web-application-type: none
  datasource:
    username: ${USER_NAME :postgres}
    password: ${PASSWORD :123}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL :BloemistBot@gmail.com}
    password: ${EMAIL_PASSWORD :x}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
google:
  credential:
    path: classpath:google_credential.json

application:
  image-url: Img/icon.ico
